name: Continuous integration

on:
  push:

jobs:
  ci:
    name: Continuous integration
    runs-on: ubuntu-latest

    steps:
      - name: "Init repo"
        uses: actions/checkout@v3

      - name: "Init node"
        uses: actions/setup-node@v3
        with:
          node-versions: '19'

      - name: "Install dependencies"
        run: npm install

      - name: "Run tests"
        run: npm run test

      - name: "Run eslint"
        run: npx eslint index.js


      - name: npm-publish
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-node@v3
            with:
              node-version: "18"
          - run: npm i
          - run: npm test
          - uses: JS-DevTools/npm-publish@v2
            with:
              token: ${{ secrets.NPM_TOKEN }}